server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}


