server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

eureka-fastpass-service:
  ribbon:
    eureka:
      enabled: true
#    listOfServers: http://localhost:37793,http://localhost:41339



