server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

spring:
  rabbitmq:
    port: 5672
    password: guest
    username: guest
    host: 127.0.0.1
  cloud:
    stream:
      bindings:
        input:
          destination: fastpasstoll
          group: tollProcessingGroup
          consumer:
            partitioned: true
      instance-count: 3
